### PR TITLE
Encrypted traffic

### PR DESCRIPTION
**Pull request by KjellKod**
- complete pull request with a pcap that sets metadata and another one that doesn't 

I changed the original code from Vaughn Adam's to fire for intermediate logger reporting as well, previously it was only for final reporting. I left the comment in there to make it obvious for the community that they can change it in case of performance need.

### CODE REVIEW

**Comment by KjellKod** [comment]
@craig-cogdill, @LogRhythm/networkmonitor-developers 

I have changed back the logic so it only fires at session end.  The reason why it didn't work for me was that I tested it in the following scenario ... (at least this is the working theory right now)

```
1 engine thread
no other traffic
every X seconds upload a tcp fluff file and the https file
```

With no other traffic the engine could not "expire" the https flow.  
When the packets were uploaded the expiration could happen but since the https pcap was re-uploaded too the Engine decided to ignore the FIN-ACK and instead continue the session.   

Technically I do consider this a bug but it's not of big importance. A better test scenario would be the following

```
1 thread
no other traffic
continous upload of 1 or more fluff pcap traffic (tcp or similar)
Only do 1 upload of the https pcap
```

I'll verify this today.

**Comment by KjellKod** [comment]
Qosmos has confirmed that they have a bug for https: https://eu3.salesforce.com/500w000001IC9Oa

**Comment by craig** [comment]
No, please revert.

**Comment by KjellKod** [comment]
Why?

**Comment by craig** [comment]
There is a security vulnerability.

**Comment by KjellKod** [comment]
? Please explain over flowdock

**Comment by craig** [comment]
The problem is you're asking the wrong craig for advice here! :P

**Comment by KjellKod** [comment]
Ha ha. Thanks. Either way we cleared it :)

**Pull request merged**
